class_name: ilms.training.GeodesicsEval
seed: 101  # indices of datapoints from test set will be randomly drawn using this seed
num_pairs: 100  # number of points to draw from test set
runs: ['/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_2', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_14', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_6', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_13', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_4', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_8', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_19', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_18', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_29', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_1', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_7', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_11', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_0', '/zhome/ef/8/160495/identifiable-latent-metric-space/model_checkpoints/icml25_celeba_baseline/celeba_hpc_seed_20']
checkpoint_names: ['best_model.pickle', 'best_model.pickle', 'best_model.pickle', 'best_model.pickle', 'best_model.pickle', 'best_model.pickle', 'best_model.pickle', 'best_model.pickle', 'best_model.pickle', 'best_model.pickle', 'best_model.pickle', 'best_model.pickle', 'best_model.pickle', 'best_model.pickle']
plot: false
geodesics_params:
  method: 'delta'
  mode: 'bruteforce'
  init_mode: 'zeros'
  init_scale: 1.0
  batch_size: 10
  n_steps: 4096
  n_poly: 10
  n_t: 256
  n_t_lengths: 256
  lr: 0.0001
  early_stopping_n: 100
  early_stopping_delta: 0.5
  warmup_steps: null
  optimizer:
    class_name: optax.sgd
    params:
      momentum: 0.9
      nesterov: true