defaults:
  - _self_
  - logging: wandb
  - inference: ensemble_geodesics
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

general:
  run_name: GEODESICS_CELEBA
  logs_folder_name: logs
  workspace: dmiai-mh
  checkpoint_path: ./geodesic_runs/${general.project_name}/${general.run_name}/
  project_name: icml_2025_celeba_geodesics
  log_code: False
  save_best: True

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
